GET http://localhost:8080/sites
Connection: keep-alive
Accept: application/json

###

POST http://localhost:8080/sites
Connection: keep-alive
Content-Type: application/json

{
  "userSeq": "13",
  "siteUrl": "t33",
  "title": "tittttta"
}


###


POST http://localhost:8080/sites
Connection: keep-alive
Content-Type: application/json

{
  "userSeq": "14",
  "siteUrl": "trythis",
  "title": "trythis!"
}


###



POST http://localhost:8080/sites
Connection: keep-alive
Content-Type: application/json

{
  "userSeq": "14",
  "siteUrl": "tyty",
  "title": "tyty!"
}

###

POST http://localhost:8080/gallery/delete?fileseq=8

###

POST http://localhost:8080/rounds?courseName=88cc
Connection: keep-alive
Content-Type: application/json
Cookie: session=NjA1ZDUyN2ItNTI0Mi00NzBiLWI0MDItMmZjMDk0ODAwMjU3;

{
  "courseName": "88cc"
}